### PR TITLE
Use bg-dark for figures when shine=dark

### PR DESCRIPTION
**Pull request by okorz001**
`<figure>` currently has bg-white hardcoded, but this doesn't look good on dark styles. This PR uses bg-dark instead when shine is dark.

For example, some generated reports such as the ones from versions-maven-plugin are hard to understand with bg-white:
darkly-bg-white

Using bg-dark makes the font awesome icon visible again:
darkly-bg-dark

It also looks good in non-black themes such as solar:
solar-bg-dark

### CODE REVIEW

**Comment by Bernardo-MG** [comment]
Thanks, I'll prepare a new version with this correction

**Comment by okorz001** [comment]
Hmm, I misunderstood what the `shine` setting controls when I made this change. 😞

I was always using `<shine>dark</shine>` with dark themes so I assumed it affected all of the body, but now I realize it was only affecting the navbar. Whether the body background is white or not is just a characteristic of the theme and independent of any skin settings (so far?). Thus I think the behavior of this PR is incorrect and just happened to work nicely for the combination of themes and settings that I was testing with.

Assuming there's no particularly smart way of using the bootstrap classes to just "do the right thing" w.r.t. the body background, then I think the best thing to do here is probably to have _yet another setting_, e.g. `figshine` or `figureshine`, so that clients can just manually pick the color that looks good for their theme.

Example of poor behavior after this PR:

```xml
      <bootswatchStyle>spacelab</bootswatchStyle>
      <shine>dark</shine>
      <bgshine>primary</bgshine>
```

image

Notice that dark and primary create a colorful navbar but have no effect on the body. After this change we are left with a jarring dark figure on a white body.

**Comment by Bernardo-MG** [comment]
I'm taking a look to it. If I have time, it will be done today. I'll be adding a new property to override figure shine.

**Comment by Bernardo-MG** [comment]
I've just published a new version. Added the figshine property for this. Just set it to white for the example you have shown me

**Pull request merged**
